name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        elixir: ["1.18.4", "1.19.5", "1.20.2"]
        otp: ["26.2.5", "27.3.4"]
        include:
          - elixir: "1.20.2"
            otp: "29.0.3"
          - elixir: "1.20.2"
            otp: "28.5"
    steps:
      - uses: actions/checkout@v6
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.24.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Restore dependencies cache
        uses: actions/cache@v5
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get --check-locked
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Credo check
        run: mix credo --strict
      - name: Format check
        run: mix format
      - name: Mix Audit check
        run: mix deps.audit
      - name: Run tests
        run: mix test
